export const DEFAULT_FORM_VALUES = {
  checking_status: '<0',
  duration: 24,
  credit_history: 'existing paid',
  purpose: 'radio/tv',
  credit_amount: 4000,
  savings_status: '<100',
  employment: '1<=X<4',
  installment_commitment: 2,
  personal_status: 'male single',
  other_parties: 'none',
  residence_since: 2,
  property_magnitude: 'car',
  age: 35,
  other_payment_plans: 'none',
  housing: 'own',
  existing_credits: 1,
  job: 'skilled',
  num_dependents: 1,
  own_telephone: 'yes',
  foreign_worker: 'yes',
};

export const FORM_SELECT_OPTIONS = {
  checking_status: ['<0', '0<=X<200', '>=200', 'no checking'],
  credit_history: ['no credits/all paid', 'all paid', 'existing paid', 'delayed previously', 'critical/other existing credit'],
  purpose: ['new car', 'used car', 'furniture/equipment', 'radio/tv', 'domestic appliance', 'repairs', 'education', 'business', 'other'],
  savings_status: ['<100', '100<=X<500', '500<=X<1000', '>=1000', 'no known savings'],
  employment: ['unemployed', '<1', '1<=X<4', '4<=X<7', '>=7'],
  personal_status: ['male div/sep', 'female div/dep/mar', 'male single', 'male mar/wid', 'female single'],
  other_parties: ['none', 'co applicant', 'guarantor'],
  property_magnitude: ['real estate', 'life insurance', 'car', 'no known property'],
  other_payment_plans: ['bank', 'stores', 'none'],
  housing: ['rent', 'own', 'for free'],
  job: ['unskilled non resident', 'unskilled resident', 'skilled', 'high qualif/self emp/mgmt'],
  own_telephone: ['none', 'yes'],
  foreign_worker: ['yes', 'no'],
};
